### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by icanzilb** [RxSwiftCommunity/RxGesture#1]
the pod right now supports only iOS. it must be relatively straight forward to add OSX support

**Comment by icanzilb** [comment]
in osx-support branch, to merge when example app is fixed

**Comment by icanzilb** [comment]
this was a tad more complicated than I initially thought because RxCocoa doesn't add "rx_event" to `NSGestureRecognizer` as it does to `UIGestureRecognizer`. Is that intentional @kzaher ?

If there isn't any concrete complication to adding `rx_event` to NSGestureRecognizer should I look into that and send a PR or do you want to take care of it, let me know.

In any case what I did to add it to NSGestureRecognizer for the moment being is a temp solution

**Comment by kzaher** [comment]
Hi @icanzilb ,

I haven't tried to do that for OSX. Didn't have time. If that interface works out on OSX as well, we could pull it into `RxCocoa` :)

**Comment by icanzilb** [comment]
I think `UIGestureRecoginizer` and `NSGestureRecognizer` are pretty much identical in behavior, it could be a nice opportunity for me to look a bit into the internals of `RxCocoa`. I'll look into it let's say ... next week :dancer:
