### ISSUE TITLE
3.0.1 not tagged & unavailable in CocoaPods

### ISSUE THREAD

**Issue by ileitch** [RxSwiftCommunity/RxGesture#101]

**Comment by shmruin** [comment]
try 

> pod 'RxGesture', :git => 'https://github.com/RxSwiftCommunity/RxGesture.git'

... and yes, I found even 3.0 is not available with cocoa pods now. it needs some update.

**Comment by ileitch** [comment]
@jegnux ping?

**Comment by jegnux** [comment]
@ileitch 3.0.1 has been released in October. It should work now.

**Comment by ileitch** [comment]
Ah, so it is. Thank you.
