### ISSUE TITLE
Build error on Xcode 11 GM with Swift Package Manager

### ISSUE THREAD

**Issue by runjuu** [RxSwiftCommunity/RxGesture#102]
> AppKit is not available when building for iOS. Consider using `#if targetEnvironment(macCatalyst)` to conditionally import this framework when building for Mac Catalyst.

Here is a [demo project](https://github.com/RxSwiftCommunity/RxGesture/files/3613469/Test.zip) to reproduce the issue

**Comment by zocario** [comment]
I have the same issue with Xcode 11, any plans to merge https://github.com/RxSwiftCommunity/RxGesture/pull/98 to fix this error? :)

**Comment by jegnux** [comment]
I merged #98 
Can you tell me if it works correctly now? I'll make a new cocoapods version then

**Comment by stami** [comment]
@jegnux I had the same issue and #98 fixed it all right.

**Comment by runjuu** [comment]
@jegnux Master branch now works well.

**Comment by jegnux** [comment]
Thanks for the feedback, I close the issue
