### ISSUE TITLE
Why set isUserInteractionEnabled = true?

### ISSUE THREAD

**Issue by ishall1** [RxSwiftCommunity/RxGesture#125]
![image](https://user-images.githubusercontent.com/8748505/129662973-fe77fea8-4d97-4a1f-88da-5887e2bcebd9.png)

I found you set **isUserInteractionEnabled = true** in **public func gesture<G: RxGestureRecognizer>(_ gesture: G) -> ControlEvent<G>** and i wonder is there any reason to do so?

**Comment by vzsg** [comment]
Disclaimer: I'm not the author of the library, but I believe the line makes sense.

If this extension function is used on a UILabel, UIImageView or otherwise non-interactive by default view, then the gesture recognizer would not fire unless you set the isUserInteractionEnabled flag to true manually. That would certainly be confusing or aggravating for the end user.

**Comment by ishall1** [comment]
> Disclaimer: I'm not the author of the library, but I believe the line makes sense.
> 
> If this extension function is used on a UILabel, UIImageView or otherwise non-interactive by default view, then the gesture recognizer would not fire unless you set the isUserInteractionEnabled flag to true manually. That would certainly be confusing or aggravating for the end user.

It seems an unexpected side effect to me. Some times  interactive of a view should be determined by business, so how can i avoid conflict in this situation?

**Comment by vzsg** [comment]
Hmm. The more I think about it, your point makes the more sense.

> As a side note, I could think of three ways to have business control things:
> - not touching the flag, but instead filtering out events on the receiving end
> - attaching/detaching the recognizer with a flatMapLatest per the enabled state (*)
> - adding a second subscription that controls the isUserInteractionEnabled flag (since the extension function only sets it to true at subscription time, this should be safe).

(*) And this is exactly what got my gears grinding: if subscription sets it to true, why doesn't unsubscribing revert it to the original state?

That being said, changing this would break applications that don't set the flag manually, which I assume most of the clients of the library...

**Comment by jegnux** [comment]
Hey @ishall1 👋 

I have to admit it was an opinionated choice and @vzsg explanation is correct, without it gesture recognizers don't work on some views like UILabel, etc...

That said, I understand your business use case and once again @vzsg is correct. The idiomatic "RxGesture" way to do it is through the Rx runtime: filtering events or disposing the subscription.
