### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by icanzilb** [RxSwiftCommunity/RxGesture#16]
Add a UI test suite to run though the example app and validate that all gestures work

**Comment by icanzilb** [comment]
tried this with Apple's UI testing framework but it seems it doesn't support all gestures :( any ideas how to test for all possible gestures anyone?

**Comment by icanzilb** [comment]
@jegnux can you address this or close it?

**Comment by jegnux** [comment]
@icanzilb I won't be able to address this alone. Not sure if I should close it though. Maybe someday, a contributor will come here and handle this like I did with some other PRs 🤔 .

**Comment by ajchili** [comment]
Would you mind if I took this on?

**Comment by jegnux** [comment]
@ajchili I started to work on it, but don't have time to go further. So for now I just set up the target and added one test.
=> https://github.com/RxSwiftCommunity/RxGesture/blob/v2.0.0/RxGesture/RxGesture-iOS-Tests/RxGestureTests.swift

You can fork the v2.0.0 branch and feel free to add more tests and make a PR (against `v2.0.0`)

Thanks 👍

**Comment by ajchili** [comment]
I'll get started on it over the weekend, thanks for the starting point

**Comment by ajchili** [comment]
@jegnux I have been busier than I expected when I first commented on this issue. I am unsure if I can still make tests but I get any free time to do so I'll PR against `v2.0.0`.

**Comment by jegnux** [comment]
@ajchili don't worry, I was myself busy and wasn't able to progress a lot on it. 
You can still add tests targeting `2.0.0`. If that branch is merged in the meantime, we'll re-target it to `master`.

**Comment by popei69** [comment]
Hey guys, is there any plan to pick this one up? I don't mind helping if it's still relevant, thanks!
