### ISSUE TITLE
Minimum deployment target '8.3'

### ISSUE THREAD

**Issue by garsdle** [RxSwiftCommunity/RxGesture#17]
I was wondering what the reason the minimum target you have in the pod spec file 8.3 and not just 8? Love the library!

**Comment by icanzilb** [comment]
to be honest I'm not sure why, it doesn't look like something I intentionally did. maybe `pod create` adds that by default? again - not sure why, looks like rxswift itself requires 8.0 so at first sight there's no need to require 8.3 for RxGesture

**Comment by lichendi** [comment]
So ,how can we fix this?

**Comment by lexrus** [comment]
Same issue here.
The framework target of RxGesture is set to iOS 9.0. Other Rx*** frameworks works fine in my iOS 8.0 project.
<img width="588" alt="screen shot 2017-05-02 at 6 12 04 pm" src="https://cloud.githubusercontent.com/assets/219689/25614029/e7c03d7c-2f62-11e7-9408-ccb891d37bc9.png">

**Comment by OrkhanAlikhanov** [comment]
@icanzilb So, why don't you lower the deployment target? Is there any specific reason?

**Comment by icanzilb** [comment]
maybe @jegnux can address this? or close the issue?

**Comment by jegnux** [comment]
@icanzilb I'll enable this on future release.
It's already done on https://github.com/RxSwiftCommunity/RxGesture/tree/feature/customizable-delegate branch, but I still want to add 2-3 things before opening a PR

**Comment by TrungPhanTiki** [comment]
I got the same problem. My app target iOS 8.0. Hope you guy fix it ASAP.

**Comment by jegnux** [comment]
Hi everyone, I've just changed the app target to iOS 8.0 in [`1.1.0` release](https://github.com/RxSwiftCommunity/RxGesture/releases/tag/1.1.0). 
Feel free to check it out :wink:
