### ISSUE TITLE
No Pinch gesture?

### ISSUE THREAD

**Issue by AndrewSB** [RxSwiftCommunity/RxGesture#19]
Was that an overthought or is it impossible to implement?

I was thinking about giving it a shot, wanted to make sure it wasn't a path that had been taken before

**Comment by icanzilb** [comment]
I don't think there is a pinch gesture support currently, but it's something I can see people having need of. If you want to go ahead - do it :) Just keep an eye on the existing code and you should be fine adding it

**Comment by jegnux** [comment]
`UIPinchGestureRecognizer` is now supported in the [`1.0.0`](https://github.com/RxSwiftCommunity/RxGesture/releases/tag/1.0.0) release. Check it out!
