### ISSUE TITLE
Underplot direct link

### ISSUE THREAD

**Issue by franciscoamado** [RxSwiftCommunity/RxGesture#2]
Hi,

Just noticed a small error. Your underplot direct link is leading to a github 404 instead of the your actual website.

Awesome idea for the pod.
Thank you,
Francisco

**Comment by icanzilb** [comment]
it was auto generated - i need to check which tool produced the 404 link

**Comment by icanzilb** [comment]
oh no - human error - mine :) fixed now - thanks
