### ISSUE TITLE
It doesn't support Swift 3 + RxSwift 3.0.0-beta.1 yet

### ISSUE THREAD

**Issue by vegidio** [RxSwiftCommunity/RxGesture#24]
RxGesture is still using the old Swift syntax that is not available by default in Xcode 8. It needs to be updated to Swift 3 + RxSwift 3 in order to continues to work.

**Comment by icanzilb** [comment]
RxSwift 3 beta just came out, but if you send a PR I can have a look

**Comment by juliengdt** [comment]
@icanzilb is it me or this issue can be closed ?
