### ISSUE TITLE
Way to access UIGestureRecognizer?

### ISSUE THREAD

**Issue by dangthaison91** [RxSwiftCommunity/RxGesture#29]
Is there any way to get GestureRecognizer? In some case i want to configure some option like: numberOfTaps, numberOfTouchs or cancelTouchInView...

I see pull request #22 could help.

**Comment by jegnux** [comment]
The new [`1.0.0`](https://github.com/RxSwiftCommunity/RxGesture/releases/tag/1.0.0) release give you access to some of these parameters on gesture creation (ex: `view.rx.tapGesture(numberOfTaps: 2)`) and even to the whole gesture recognizer thanks to the `configure: ((GestureRecognizer) -> Void)` parameter. Check it out!
