### ISSUE TITLE
RxSwift version conflicts with Moya

### ISSUE THREAD

**Issue by retsohuang** [RxSwiftCommunity/RxGesture#38]
```
[!] Unable to satisfy the following requirements:

- `RxSwift (~> 3.0.0)` required by `RxGesture (0.2.0)`
- `RxSwift (~> 3.1.0)` required by `Moya/RxSwift (8.0.0)`
```

**Comment by freak4pc** [comment]
This is probably due to a min-version dependency issue that was resolved but not pushed to Cocoapods. 

Try replacing the RxGesture line in your Podfile to

`'RxGesture', :git =>'https://github.com/RxSwiftCommunity/RxGesture.git'`

**Comment by retsohuang** [comment]
Oops, I haven't noticed that commit wasn't published, works now, thanks.

**Comment by freak4pc** [comment]
Anyone up to pushing the updated Spec ? @icanzlib

**Comment by icanzilb** [comment]
yeah, let me have a look
