### ISSUE TITLE
tapGesture call in UILabel and it's parent view when i touch on UILabel

### ISSUE THREAD

**Issue by haitacnj** [RxSwiftCommunity/RxGesture#43]
i touch on my label to do something and touch on it's parent view to dismiss popup ,...dismiss popup always call

**Comment by jegnux** [comment]
@haitacnj You should set a delegate on each of your gesture recognizer:
```swift
superview.tapGesture(configuration: { $0.delegate = self }).when...
label.tapGesture(configuration: { $0.delegate = self }).when...
```

and implement the following method:
```swift
func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool
```

**Comment by haitacnj** [comment]
@jegnux thank you, but in "gestureRecognizer" method 

> true to allow both gesture​Recognizer and other​Gesture​Recognizer to recognize their gestures simultaneously. The default implementation returns false—no two gestures can be recognized simultaneously.

both subscribe call back not call if  return false

**Comment by jegnux** [comment]
@haitacnj can you give some code please?

**Comment by haitacnj** [comment]
![popup_rxgesture](https://cloud.githubusercontent.com/assets/3365969/24340954/5d27a7f2-12e0-11e7-8e8b-97bf537d58da.png)

@jegnux this's my case
(1) is always called although i touch on UILabel 1.
If (4) return false , nothing happen, both (1) and (3) aren't called
I hope only (3) to be called when i touch on UILabel1

Release 0.2.1 works perfectly, no need to to anything :) i keep using it 

Thank,
- Note:
Release 1.0.0 is great but sometimes it doesn't work properly ( sometime subscribe twice in my UITableViewCell )

**Comment by jegnux** [comment]
@haitacnj Keep the delegate only for the first gesture recognizer, then try to implement the following delegate method: 
```swift
func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRequireFailureOf otherGestureRecognizer: UIGestureRecognizer) -> Bool {
    if gestureRecognizer.view == self.view {
         return true
    }
    return false
}
```
Also, don't forget to remove the implementation of 
```swift
func gestureRecognizer(_:,shouldRecognizeSimultaneouslyWith:) -> Bool
```

**Comment by haitacnj** [comment]
@jegnux thank you 👍
