### ISSUE TITLE
PermissiveGestureRecognizerDelegate should be public.

### ISSUE THREAD

**Issue by ozgur** [RxSwiftCommunity/RxGesture#44]
We have `PermissiveGestureRecognizerDelegate` implemented but it is not used internally anywhere in the code. I believe it should be defined as public.

**Comment by jegnux** [comment]
@ozgur 
It is used if the gesture recognizer doesn't have already a delegate: [View+RxGesture.swift:L92](https://github.com/RxSwiftCommunity/RxGesture/blob/master/Pod/Classes/View%2BRxGesture.swift#L92)

Moreover, it's just a simple class with only one implemented method. I don't see any use case where this would be useful outside of *RxGesture*. What do you have in mind?

**Comment by ozgur** [comment]
Oh, that's good. I haven't seen that. I wanted to use it to save myself the trouble of implementing `shouldRecognizeSimultaneouslyWith` method. I was going to do sth like below:

    let configuration: (UIGestureRecognizer) -> () = { recognizer in
      recognizer.delegate = PermissiveGestureRecognizerDelegate.shared
    }

    mapView.rx.panGesture(configuration: configuration)
      .when(.began, .changed)
      .bindTo(...)
      .addDisposableTo(rx_disposeBag)

**Comment by jegnux** [comment]
@ozgur oh I see. Indeed you don't have to do this as it's the default behavior.

I close the issue.
