### ISSUE TITLE
Discern single from double tap

### ISSUE THREAD

**Issue by karpov3** [RxSwiftCommunity/RxGesture#46]
Hi,
in my view i have to actions, single and double tap.

`self.view.rx
            .tapGesture(numberOfTapsRequired: 2)
            .when(.recognized)
            .subscribe(onNext: { value in

            })
            .addDisposableTo(disposeBag)`

How can I discern them, because Singe and Double always triggers toghether?

**Comment by jegnux** [comment]
@karpov3 It's a similar problem to #43 

1. Set the delegate for the single tap gesture:
```swift
view.rx.tapGesture(configuration: { $0.delegate = self }).when... // single tap => delegate
view.rx.tapGesture(numberOfTapsRequired: 2).when... // double tap => no delegate
```

2. Implement this:
```swift
func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRequireFailureOf otherGestureRecognizer: UIGestureRecognizer) -> Bool {
    if let gesture = otherGestureRecognizer as? UITapGestureRecognizer, gesture.numberOfTapsRequired == 2 {
         return true
    }
    return false
}
```

**Comment by karpov3** [comment]
@jegnux Thank you, good solution!
