### ISSUE TITLE
Subscribe several times

### ISSUE THREAD

**Issue by haitacnj** [RxSwiftCommunity/RxGesture#49]
I use tapGesture in TableView and it calls several times. 

```swift
cell.ibPlaySound.rx.tapGesture().when(.recognized).subscribe(onNext: {   val  in
                print("play sound....")
}).addDisposableTo(self.binBag)
```
Touch once and call  3 (or 2) times
play sound....
play sound....
play sound....

**Comment by jegnux** [comment]
@haitacnj Your cell is reusable, so everytime it's reused, you subscribe to it again. So the more it's reused, the more you will perform your subscribe onNext closure.

One solution could be to add a `reusableBag` in your cell subclass and clean it in `prepareForReuse`:
```swift
class MyCell: UITableViewCell {
    var reusableBag = DisposeBag()
    override func prepareForReuse() {
        super.prepareForReuse()
        reusableBag = DisposeBag()
    }
}
```

and add your disposeable in this bag: 
```swift
cell.ibPlaySound.rx.tapGesture().when(.recognized).subscribe(onNext: { val in
print("play sound....")
}).addDisposableTo(cell.reusableBag)
```

PS: I close this as it's not really related to RxGesture, but feel free to reopen it if needed.
