### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by mgurreta** [RxSwiftCommunity/RxGesture#52]
Don't forget carthage users!! :)

**Comment by jegnux** [comment]
@mgurreta Carthage should work with RxGesture

What happened?

Or maybe you added this issue only because we don't mention Carthage support on README?

**Comment by mgurreta** [comment]
yeah. it's only because there is no mention on the readme file. apart from that this extension to Rx it's super awesome. thanks

**Comment by jegnux** [comment]
Ok, I'll add it to readme then, you're right. Thanks for this report.

**Comment by mgurreta** [comment]
thanks @jegnux!! :)

**Comment by mgurreta** [comment]
fixed with https://github.com/RxSwiftCommunity/RxGesture/pull/53

**Comment by jegnux** [comment]
Thanks 👍
