### ISSUE TITLE
Carthage build is broken

### ISSUE THREAD

**Issue by OSemenovBoyarka** [RxSwiftCommunity/RxGesture#55]
Thanks for the great library!

I'm trying to install it via Carthage using
`carthage update --platform iOS` and constantly get following error: 
`#import "Headers/RxCocoa-Swift.h"
        ^
/Volumes/Workspace/ololo/Carthage/Checkouts/RxGesture/RxGesture/../Carthage/Build/Mac/RxCocoa.framework/Headers/RxCocoa-Swift.h:136:9: error: module 'AppKit' not found
@import AppKit;
        ^
<unknown>:0: error: could not build Objective-C module 'RxCocoa'`

**Comment by jegnux** [comment]
Hi @SemenovAlexander  
I've just published a [`1.1.0` release](https://github.com/RxSwiftCommunity/RxGesture/releases/tag/1.1.0) that should fix this issue.

Thanks for your contribution and feel free to check if everything works correctly for you.
