### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by sidmani** [RxSwiftCommunity/RxGesture#57]
Just wondering if there are any plans for Swift 4/Xcode 9 support. The library currently doesn't compile under Swift 4, but I can fix it and create a pull request if someone with write access makes a swift-4 branch for me to compare against.

**Comment by sidmani** [comment]
https://github.com/sidmani/RxGesture/tree/swift-4 contains all necessary changes. I don't know much about Carthage, so I left that untouched, but I updated the podspec to depend on RxSwift and RxCocoa 4.0.0-alpha.0.

**Comment by jegnux** [comment]
Thanks @sidmani I'll try to look into your PR. Ideally I would have waited to have `RxSwift 4` out of alpha/beta before updating `RxGesture`. 

I wonder how other @RxSwiftCommunity/contributors handle this?

**Comment by icanzilb** [comment]
@jegnux rxswift4 is still an alpha pre-release, I'm waiting for a stable beta before updating my libs

**Comment by sidmani** [comment]
@jegnux I would have waited too, but there's an issue (or maybe it's the intended behavior, the cocoapods team hasn't responded to me) with cocoapods which causes "4.0.0-alpha.1" to not satisfy the requirement "~> 3.4" for RxSwift, so having a swift-4 branch with updated dependencies would be convenient to avoid git submodules.

**Comment by sidmani** [comment]
None of the changes I made were RxSwift-related, only Swift 4 updates.

**Comment by jegnux** [comment]
@sidmani can't you use RxSwift 3.x and RxGesture 1.1.x until RxSwift 4 come's out?

**Comment by freak4pc** [comment]
@jegnux @sidmani In general Swift 4 should hit final tomorrow with the release of iOS 11 and iPhone 8/X/whatever, so we can hold on this and see if this PR is still relevant

**Comment by xushao1990** [comment]
👍

**Comment by Plnda** [comment]
Still cannot update to the latest 4.0 rxswift version since I have this error 
`
RxSwift (= 4.0.0-beta.0) required by Podfile
RxSwift (~> 4.0.0-beta.0) required byRxCocoa (4.0.0-beta.0)
RxSwift (~> 3.6) required by RxGesture (1.1.1)
`

**Comment by EvsenevDev** [comment]
@jegnux 
Hi, i tried add migration to Swift 4 with RxSwift 4 beta, but i have issues with *Defaults* enums, thats couldn't be used for default values of init parama. I can do that without enums and help you add this migration, i'm interested, but i want hear your solution. What do you think? 

Thanks

**Comment by sidmani** [comment]
@EvsenevDev look at my fork

**Comment by jegnux** [comment]
@EvsenevDev what is your solution "without enum"?

Is it better than @sidmani's? (public `Defaults` here the enum name is prefixed by the kind of Defaults)

**Comment by EvsenevDev** [comment]
@sidmani @jegnux ok. Will you merge it?

**Comment by sidmani** [comment]
@EvsenevDev @jegnux I need a swift4 branch to compare against (unless you want me to use master?)

**Comment by jegnux** [comment]
@sidmani I just created `swift-4` branch.

**Comment by adamsmaka** [comment]
is it possible to use it alongside RxSwift 4.0 ?

**Comment by worthbak** [comment]
Any status update on the Swift 4 branch? Looks like RxSwit 4.0 just dropped.

**Comment by bobgodwinx** [comment]
@worthbak there is `Swift 4.0` branch you point your pod to that branch for the time being

**Comment by jegnux** [comment]
```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  RxGesture (1.2.0) successfully published
 📅  October 19th, 10:54
 🌎  https://cocoapods.org/pods/RxGesture
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

Thank you all for your contributions 🙏
