### ISSUE TITLE
multiple SwipeGestures

### ISSUE THREAD

**Issue by plm75** [RxSwiftCommunity/RxGesture#70]
Hello, thanks for this library.

I'm trying to recognise multiple swipe gestures on the same view and create an observable of the latest recognised swipe's direction.

I can do it with an Observable.merge but it is pretty verbose and I was hopping to be able to do something like:

`let observableDirection = self.view.rx.swipeGesture([.left, .right, .up, .down]).when(.recognized).map { $0.direction }
`

but that doesn't seem to work: up and down events are not emitted and left and right return a direction with rawValue of 15

Not sure if this is a bug or if I missed something ?

**Comment by jegnux** [comment]
Oh, that's interesting. It seems it's a known "bug" (or feature?) of `UISwipeGestureRecognizer`.
We can find questions about that on StackOverflow [here](https://stackoverflow.com/questions/24215117/how-to-recognize-swipe-in-all-4-directions), [here](https://stackoverflow.com/questions/3319209/setting-direction-for-uiswipegesturerecognizer) or [here](https://stackoverflow.com/questions/8181774/how-to-recognize-swipe-in-all-4-directions).

As I use in RxGesture the standard `.direction` property, it's normal that you get the result you describe.

Until I workaround this in the library, I suggest you to use the `merge` operator. As you said it's quite verbose, but I don't have anything better for now.

**Comment by plm75** [comment]
Ok then, 

Thanks!

**Comment by jegnux** [comment]
I keep this open. I already started to work on it. I don't know when it'll be ready though.
