### ISSUE TITLE
RxGesture on containing view + UICollection's didSelect

### ISSUE THREAD

**Issue by plm75** [RxSwiftCommunity/RxGesture#72]
Hello, I hope it is ok to ask a question here.

I have a collectionView with multiple types of cells.
One type is cells containing a TextView
Another type is cells  with just a label.

I want to handle taps on the label cells by implementing the collectionView's `didSelectItemAtIndexPath` method.

I also want to dismiss the keyboard when there's a tap outside the textView with the following:

    self.view.rx.tapGesture().when(.recognized)
      .subscribe(onNext: { [weak self] _ in self?.view.endEditing(true })
      .disposed(by: disposeBag)

When I do this, however, the collectionView's didSelect method is not called anymore.

How do I set RxGesture to handle taps on the view and still pass on the tap event to whichever object might want to handle it down the chain ?

**Comment by melpup** [comment]
I have a similar issue to the one you had.

The following code allowed the tap gesture to propagate down to the UICollectionView's didSelect method:
```
self.view.rx
            .tapGesture(numberOfTouchesRequired: 1, numberOfTapsRequired: 1, configuration: { (rec, _) in
                rec.cancelsTouchesInView = false
            })
            .when(.recognized)
            .subscribe(onNext: { [weak self] _ in self?.view.endEditing(true) })
            .disposed(by: disposeBag)
```

I just tried to set **cancelsTouchesInView** to false.
More details here: [https://developer.apple.com/documentation/uikit/uigesturerecognizer/1624218-cancelstouchesinview](url)

**Comment by plm75** [comment]
👍 Thanks @melpup

**Comment by melpup** [comment]
You're welcome @plm75

**Comment by felipericieri** [comment]
Just came across it, very useful! Thanks!
