### ISSUE TITLE
How to distinguish tap from scroll in scrollView?

### ISSUE THREAD

**Issue by nominalista** [RxSwiftCommunity/RxGesture#75]
I noticed different behavior between this two parts of code:
1. view.rx.tapGesture().when(.recognized).subscribe(onNext: { _ in
       self.doSomething()
   }).disposed(by: disposeBag)

2. view.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(doSomething)))

The difference is that (this view is added to UIScrollView) when the user scrolls and taps to stop scrolling 1. approach calls doSomething(), but 2. approach doesn't call doSomething().

For user experience 2. is better, because view is tapped unwittingly in 1. approach while scrolling. 
Where does the difference come from? I assume that I should use check simultaneousRecognitionPolicy somehow?

**Comment by jegnux** [comment]
@Nominalista yes I guess it's because RxGesture allows by default simultaneous gesture recognizers. you can change this by using your own delegate or by changing the `simultaneousRecognitionPolicy` of default delegate.

**Comment by nominalista** [comment]
delegate.simultaneousRecognitionPolicy = .never helped! Thanks for help.
