### ISSUE TITLE
Any plans on supporting custom UIGestureRecognizer subclasses?

### ISSUE THREAD

**Issue by JohnEstropia** [RxSwiftCommunity/RxGesture#77]
In particular, specialized gestures that extend the default UIKit subclasses

**Comment by jegnux** [comment]
@JohnEstropia I don't understand...
RxGesture supports all gestures defined by UIKit.
Also, the API is extensible so if in your projects, you want to support your own gesture recognizer, it's possible. 

You can do:
```swift
let gesture = SpecializedGestureRecognizer()
view.rx.gesture(gesture).when(.recognized).subscribe(onNext: { g in
...
})
```

You can also implement the same shortcuts as ones provided by RxGesture with native recognizer. You can inspire yourself with this implementation: https://github.com/RxSwiftCommunity/RxGesture/blob/master/Pod/Classes/iOS/UITapGestureRecognizer%2BRxGesture.swift

**Comment by JohnEstropia** [comment]
Sorry if I wasn't clear. First, thanks for mentioning the `gesture(...)` factory method that accepts a `UIGestureRecognizer` instance directly, I am now using that for my implementation.

I guess when I first asked the question I was looking for a factory method that lets me configure the `RxGestureRecognizerDelegate` without having to create my own concrete `GestureRecognizerFactory`. Now I found the `gesture(_:)` method, my suggestion now is wouldn't it be convenient to have an overload method `gesture(_:configuration:)` where we can configure the `RxGestureRecognizerDelegate` policies?

**Comment by jegnux** [comment]
Hum it would be possible, but as this operator can take any gesture recognizer, I don't feel comfortable  by overriding it's delegate. I could check if there's already a delegate and set it to `RxGestureRecognizerDelegate` only if there isn't already one, but I don't really like this.
What you could do is to use it by yourself:
```swift
let gesture = SpecializedGestureRecognizer()
let delegate = RxGestureRecognizerDelegate()
gesture.delegate= delegate
view.rx.gesture(gesture).when(.recognized).subscribe(onNext: { g in
...
})
```

But you'll have to maintain a strong reference to it, otherwise it will be dealloc immediately because `gesture.delegate` is a weak reference.

**Comment by jegnux** [comment]
@JohnEstropia Hey,

I think this should be doable now with RxGesture 2.x:

```swift
class MyCustomGestureRecognizer : UIGestureRecognizer {
    // ...
}

public typealias CustomGestureConfiguration = Configuration<MyCustomGestureRecognizer>
public typealias CustomGestureControlEvent = ControlEvent<MyCustomGestureRecognizer>
public typealias CustomGestureObservable = Observable<MyCustomGestureRecognizer>

extension Factory where Gesture == GestureRecognizer {
    public static func custom(configuration: CustomGestureConfiguration? = nil) -> AnyFactory {
        return Factory(configuration: configuration).abstracted()
    }
}

public extension Reactive where Base: View {
    public func customGesture(configuration: CustomGestureConfiguration? = nil) -> TapControlEvent {
        return gesture(Factory(configuration: configuration))
    }
}
```
