### ISSUE TITLE
Is it possible to subscribe to UIButton UIControlEvents(.touchUpInside, .touchDown, .touchUpOutside, etc..)?

### ISSUE THREAD

**Issue by dimaosa** [RxSwiftCommunity/RxGesture#80]
Hi here, 

Is it possible to subscribe to UIButton UIControlEvents(.touchUpInside, .touchDown, .touchUpOutside, etc..)?

otherwise there is still need to write boilerplate
```
button.addTarget(self, action: #selector(buttonPressed), for: .touchUpInside)
button.addTarget(self, action: #selector(buttonDown), for: .touchDown)
button.addTarget(self, action: #selector(buttonUp), for: .touchCancel)
button.addTarget(self, action: #selector(buttonUp), for: .touchUpOutside)
```

for example right now I can subscribe to `.rx.tapGesture().asControlEvents...` but this will give me only UITapGestrureRecognizer 😞.

**Comment by jegnux** [comment]
This out of scope of RxGesture but if I understand correctly, what you want is already possible with RxCocoa: 
```swift
button.rx.controlEvent(.touchUpInside),
button.rx.controlEvent(.touchDown),
button.rx.controlEvent(.touchCancel),
button.rx.controlEvent(.touchUpOutside)
```

**Comment by dimaosa** [comment]
yeah, exactly, thank you @jegnux . Hmm, I thought it was related to RxGesture.
