### ISSUE TITLE
Forgotten gesture configuration in latest release (2.0.0)

### ISSUE THREAD

**Issue by svyatoslav-zubrin** [RxSwiftCommunity/RxGesture#84]
It looks like 'configuration'-parameter passed to public initializers of swipe gesture is simply forgotten/skipped. I've created pull request #83 with a fix. Haven't checked the rest of gestures though.

**Comment by jegnux** [comment]
Indeed, thanks for catching.
I just merged your PR and I'm preparing a 2.0.1 release 😉

**Comment by jegnux** [comment]
@svyatoslav-zubrin You can update :)
<img width="429" alt="capture d ecran 2018-09-26 a 17 09 43" src="https://user-images.githubusercontent.com/63070/46089521-fee9b700-c1ae-11e8-8656-903e54fa11ea.png">
