### ISSUE TITLE
Make tapGesture more simple

### ISSUE THREAD

**Issue by o-nnerb** [RxSwiftCommunity/RxGesture#90]
`
extension Reactive where Base: UIView {
    var tap: ControlEvent<Void> {
        return ControlEvent(events: self.tapGesture().when(.recognized).map { _ -> Void in return })
    }
}
`

**Comment by o-nnerb** [comment]
This way, we just need to do this view.rx.tap.subscribe(onNext: {...}).disposed(by: ...)

**Comment by jegnux** [comment]
@brennobemoura Unfortunately, this will conflict with `UIButton.rx.tap`.

**Comment by o-nnerb** [comment]
Well, the first time that I try to extend the `RxGesture`, returning the same type of `UIView.rx.tapGesture()`, I got the error. But, returning the same type `ControlEvent<Void>`, swift handle the conflit with no problem. I don't know if it's because I'm using swift 5, but this worked for me.

**Comment by o-nnerb** [comment]
You can check if the error will occur by adding the extension that I post at the beginning.

**Comment by jegnux** [comment]
Hum indeed, maybe this isn't an issue.

However, I'm still not convinced by such addition. I don't see why we should have an exceptional syntax for the tap, but not for other gesture recognizers. Also it will create an inconsistency in the API where for one gesture you're not required to use the `.when(.recognized)`, but for other you do.

One of the swift guildelines is to prefer clarity over brievety, and here I think having a consistent API accross all gesture recongnizer brings some clarity. Requiring to explicetely use `.when(.recognized)` brings also some clarity about what's going on. No unnecessary hidden magic here.

**Comment by o-nnerb** [comment]
I think that's because I was using too much Reactive and, when I use the RxGesture, I was trying the follow the same pattern for UIButton. You're totally right.
