### ISSUE TITLE
RxSwift & RxCocoa 5 compatibility?

### ISSUE THREAD

**Issue by Ariandr** [RxSwiftCommunity/RxGesture#91]
Hi.
Now I cannot use RxGesture with recently released RxSwift & RxCocoa 5. (https://github.com/ReactiveX/RxSwift/releases)
It requires RxCocoa 4.5.

Any updates on compatibility plans? Thank you.

![Screenshot at Apr 30 14-51-04](https://user-images.githubusercontent.com/13591333/57063899-70ea2780-6ccd-11e9-8bd8-393e25988b00.png)

**Comment by trispo** [comment]
@Ariandr You can use this modified podspec I created for now: https://gist.github.com/trispo/29ec5dfefca0ecf8a57fc2f3fc3c4956

Use it like this in your Podfile:
```pod "RxGesture", :podspec => "https://gist.githubusercontent.com/trispo/29ec5dfefca0ecf8a57fc2f3fc3c4956/raw/bf3f85d6762405e98a638080909d19cb65c35f61/RxGesture.podspec"```

**Comment by Ariandr** [comment]
@trispo Thanks!
For me it's not critical right now, I will wait for the official update to be released. This temporary fix will be important for many users, though :)

**Comment by DanielAsher** [comment]
`carthage update --no-build --verbose --new-resolver` with RxSwift and RxGesture dependencies hangs for me.

**Comment by hucool** [comment]
I have the same problem

**Comment by iwheelbuy** [comment]
any progress?

**Comment by adamcichy** [comment]
the https://github.com/RxSwiftCommunity/RxGesture/pull/92 PR is merged. what's the ETA for next release?

**Comment by cliss** [comment]
+1. Would really love to see a new release as this is holding me up as well.

**Comment by Ariandr** [comment]
Guys, the new version is released, thanks!
https://github.com/RxSwiftCommunity/RxGesture/releases

I close the issue :)
