### ISSUE TITLE
tapGesture in subview and self both triggered

### ISSUE THREAD

**Issue by MrQQQQQQQQQQ** [RxSwiftCommunity/RxGesture#93]
the demo is :

let sub = UIImageView.init(frame: CGRect.init(x: 0, y: 0, width: 200, height: 200))
        sub.rx.tapGesture().when(.recognized).subscribe(onNext: { (tap) in
            
            print("sub tap is \(tap)")
            
        }).disposed(by: disposeBag)
        
        self.view.addSubview(sub)
        
        self.view.rx.tapGesture().when(.recognized).subscribe(onNext: { (tap) in
            
            print("self tap is \(tap)")
            
        }).disposed(by: disposeBag)

when i touch in subview,  both tap gesture triggered,  Are there any mistakes here？

**Comment by jegnux** [comment]
It's the expected behavior. 

To change this, you can configure the gesture delegate as explained here: https://github.com/RxSwiftCommunity/RxGesture#delegate-customization

**Comment by MrQQQQQQQQQQ** [comment]
thanks !
I changed it to this  
 self.view.rx.tapGesture(configuration: { (gesture, delegate) in
            delegate.simultaneousRecognitionPolicy = .never
        }).when(.recognized).subscribe(onNext: { (tap) in
        print("self tap is \(tap)")
    }).disposed(by: disposeBag)

and it works !
