### ISSUE TITLE
RxGesture podspec does not specify a Swift version.

### ISSUE THREAD

**Issue by ileitch** [RxSwiftCommunity/RxGesture#94]
I'm getting this error during `pod install`:

```
[!] Unable to determine Swift version for the following pods:

- `RxGesture` does not specify a Swift version and none of the targets (`MyTarget`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

There's actually two issues here:
1. RxGesture doesn't set `swift_version` in the podspec.
2. CocoaPods is mistaken that `MyTarget` doesn't set `SWIFT_VERSION` - it does, but only via an xcconfig file.

The CocoaPods bug is likely going to be more complex to resolve, so would you mind adding `swift_version` to the podspec in the mean time?

**Comment by kaminisea** [comment]
I sent PR which could solve a part of this problem ✌️
I confirmed that the example of this project works normally in the following environment, so it may be useful to refer to it 👍
`
macOS: 10.14.5
Xcode: 10.2.1
Swift: 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
`
