### ISSUE TITLE
Swiftlint proposal

### ISSUE THREAD

**Issue by M0rtyMerr** [RxSwiftCommunity/RxGesture#95]
Swiftlint became the golden standard for providing unified code style for projects. 
What do you think about adding swiftlint to project (with build phase)?
Config from the main repo could be used - https://github.com/ReactiveX/RxSwift/blob/master/.swiftlint.yml
It will be a pleasure for me to open PR :)

**Comment by jegnux** [comment]
@MortyMerr I think it's a good idea. Usually, the hardest part is to settle on what rules we should enable or not. But as there's already a main repo config, it's a no brainer :)

**Comment by M0rtyMerr** [comment]
https://github.com/RxSwiftCommunity/RxGesture/pull/96

**Comment by jegnux** [comment]
Thanks @MortyMerr 🙏
